### PR TITLE
[feat] hasPreviousValue getter

### PR DESCRIPTION
**Pull request by manuel-plavsic**
This PR adds the `hasPreviousValue` getter suggested in https://github.com/nank1ro/solidart/pull/27#issuecomment-1588990715.

It is a bit unclear to me whether or not I should make a `reportObserved` call before returning `_hasPreviousValue` (similarly to what the `previousValue` getter does).

### CODE REVIEW

**Comment by manuel-plavsic** [comment]
Done :)

**Comment by nank1ro** [comment]
Thank you so much for your contributions, I really appreciate it! 👏

**Review by nank1ro — APPROVED** [review]

**Comment by manuel-plavsic** [comment]
Btw, I think that we still need a getter, otherwise one could manually change the value of `hasPreviousValue`, for example:

```dart
  @override
  void initState() {
    super.initState();
    counter = createSignal(0);
    counter.hasPreviousValue = true;
  }
```

I will make another PR soon if it is fine for you.

That is so good to hear, thanks! I really enjoy contributing to this amazing library! Btw, I sent you a DM on Twitter a few days ago ;)

**Comment by nank1ro** [comment]
You're right I hadn't thought about it that the value can be changed from outside.

Maybe you can put a getter in the `ReadSignal` that returns false.
Then in the `Signal` you may have a private `_hasPreviousSignal` value and the override the getter returning this private variable.

I didn't get any DM on Twitter 😕 , this is my profile https://twitter.com/nank1ro

**Comment by manuel-plavsic** [comment]
I have a question regarding the next pull request: why should the getter in `ReadSignal` return false instead of "correctly" returning true or false. Also, I don't understand why `previousValue` is a getter that returns null. I see that it has something to do with it being a `ReadSignal` and not a `WriteSignal`, but the value held by the `ReadSignal`  can also change.

**Comment by nank1ro** [comment]
Don't worry I'm going to do the PR myself cause I have to release a new dev.

**Pull request merged**
