### PR TITLE
[Chore] Replace deprecated methods of ErrorReporter

### PR DESCRIPTION
**Pull request by manuel-plavsic**
I just replaced the deprecated methods.

### CODE REVIEW

**Comment by nank1ro** [comment]
Are you using the latest stable of Flutter?

**Comment by manuel-plavsic** [comment]
The latest `main`:

```
> flutter --version
Flutter 3.28.0-2.0.pre.38587 • channel main • https://github.com/flutter/flutter.git
Framework • revision b15625ca92 (35 hours ago) • 2024-12-27 15:26:24 -0800
Engine • revision b15625ca92
Tools • Dart 3.7.0 (build 3.7.0-267.0.dev) • DevTools 2.41.0
```

**Comment by manuel-plavsic** [comment]
I probably should test if the changes work also with `master`, same for the other branch

**Comment by nank1ro** [comment]
> I probably should test if the changes work also with `master`, same for the other branch

See https://github.com/nank1ro/solidart/pull/99#issuecomment-2564681151

**Pull request merged**
