### PR TITLE
[Chore] Fix problems detected by VSCode

### PR DESCRIPTION
**Pull request by manuel-plavsic**
This PR fixes all the remaining problems that VSCode detects (note: I used the main channel, maybe some of the warnings do not appear yet on stable).

I was unsure whether to remove the keys entirely or to replace

```
ignore: unused_element
```

with the new:

```
ignore: unused_element_parameter
```

Since the keys are not used and it may be slightly confusing to keep them, I decided to remove them.

### CODE REVIEW

**Comment by nank1ro** [comment]
Are you using the latest stable of Flutter?

**Comment by manuel-plavsic** [comment]
The latest `main`:

```
flutter --version
Flutter 3.28.0-2.0.pre.38587 • channel main • https://github.com/flutter/flutter.git
Framework • revision b15625ca92 (35 hours ago) • 2024-12-27 15:26:24 -0800
Engine • revision b15625ca92
Tools • Dart 3.7.0 (build 3.7.0-267.0.dev) • DevTools 2.41.0
```

**Comment by nank1ro** [comment]
The problem is that they deprecated and replaced stuff of main, but on stable the new stuff is not there yet, this PR cannot land

**Review by nank1ro — APPROVED** [review]
LGTM

**Pull request merged**
